
@baseURL = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name test
GET {{baseURL}}/test

###

POST {{baseURL}}/accounts
Content-Type: application/json

{
    "name": "Bruno Gabriel",
    "email": "bruno@gmail.com",
    "password": "3789"
}

###

# @name authenticate
POST {{baseURL}}/sessions
Content-Type: application/json

{
    "email": "bruno@gmail.com",
    "password": "3789"
}

###

# @name create_question
POST {{baseURL}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "title": "Nova pergunta 2",
    "content": "Conteúdo da pergunta"
}

###

# @name get_recent_questions
GET {{baseURL}}/questions?page=2
Content-Type: application/json
Authorization: Bearer {{authToken}}